Unifik\MailChimpBundle\Entity\SubscriberList:
  type: entity
  table: MailChimpSubscriberList
  repositoryClass: Unifik\MailChimpBundle\Entity\SubscriberListRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
  lifecycleCallbacks: {  }