Unifik\MailChimpBundle\Entity\SubscriberListTranslation:
  type: entity
  table: MailChimpSubscriberListTranslation
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    listId:
      type: string
      length: 255
    name:
      type: string
      length: 255