parameters:
#    egzakt_mail_chimp.example.class: Egzakt\MailChimpBundle\Example

services:
#    egzakt_mail_chimp.example:
#        class: %egzakt_mail_chimp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
